site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
  font:
    text: Roboto
  icon:
    admonition:
      type: material/alert-circle
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


# Code block
markdown_extensions:
  # Code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search